# Pytorch test
Some random tests to get used to pytorch

In [2]:
import torch

x = torch.empty(3,4)
print(x)

tensor([[ 1.1985e+36,  3.0673e-41,  6.5179e+37,  3.0673e-41],
        [-4.0412e-21,  4.5768e-41,  1.4013e-45,  0.0000e+00],
        [ 1.6816e-44,  0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [3]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
torch.ones(4,3) * 5

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])

In [5]:
torch.manual_seed(42)

torch.rand(3,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [6]:
r = (torch.rand(3,3) - .5) *2

print("Random tensor: ")
print(r, "\n")

print("Absolute values: ")
print(torch.abs(r), "\n")

print("Inverse sine values: ")
print(torch.asin(r), "\n")

print("Determinante: ")
print(torch.det(r), "\n")

print("SVD: ")
print(torch.svd(r), "\n")

print("Standard mean: ")
print(torch.std_mean(r), "\n")

print("Maximum: ")
print(torch.max(r), "\n")

Random tensor: 
tensor([[ 0.7388,  0.1354,  0.4822],
        [-0.1412,  0.7709,  0.1478],
        [-0.4668,  0.2549, -0.4607]]) 

Absolute values: 
tensor([[0.7388, 0.1354, 0.4822],
        [0.1412, 0.7709, 0.1478],
        [0.4668, 0.2549, 0.4607]]) 

Inverse sine values: 
tensor([[ 0.8313,  0.1358,  0.5032],
        [-0.1417,  0.8802,  0.1484],
        [-0.4857,  0.2577, -0.4788]]) 

Determinante: 
tensor(-0.1522) 

SVD: 
torch.return_types.svd(
U=tensor([[-0.7804, -0.2772,  0.5604],
        [ 0.1120, -0.9438, -0.3109],
        [ 0.6151, -0.1799,  0.7676]]),
S=tensor([1.0983, 0.8331, 0.1664]),
V=tensor([[-0.8009,  0.0149,  0.5987],
        [ 0.1251, -0.9735,  0.1917],
        [-0.5856, -0.2284, -0.7777]])) 

Standard mean: 
(tensor(0.4597), tensor(0.1624)) 

Maximum: 
tensor(0.7709) 



In [8]:
# random tensor in the shape of r
torch.rand_like(r, dtype=torch.float16)

tensor([[0.1348, 0.5781, 0.2241],
        [0.6528, 0.0103, 0.1230],
        [0.3647, 0.4180, 0.7734]], dtype=torch.float16)

In [13]:
a = torch.Tensor([[1,2],
                  [3,4]])

torch.mm(a,a) # short for .matmul

tensor([[ 7., 10.],
        [15., 22.]])

In [14]:
a = torch.Tensor([[1,2],
                  [3,4]])

a*a

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [15]:
torch.eq(a,a)

tensor([[True, True],
        [True, True]])

In [18]:
assert a is a

In [21]:
b = a.clone()
c = a

print("ID of a: ", id(a))
print("ID of b: ", id(b))
print("ID of c: ", id(c))

ID of a:  140280552221808
ID of b:  140280562802176
ID of c:  140280552221808


In [24]:
import numpy as np

# from numpy matrix to pytorch tensor
numpy_array = np.ones((2,3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [25]:
# from pytorch tensor to numpy matrix
pytorch_rand = torch.rand(2,3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890]])
[[0.3423134  0.63434184 0.36441028]
 [0.7104288  0.9464111  0.7890298 ]]
